version: '2'
services:

  jekyll-gulp:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ARG_PIP_INDEX_URL: ${PIP_INDEX_URL}
        ARG_PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        http_proxy:
    image: muccg/jekyll-gulp
